# Generated by Django 4.2.4 on 2023-09-13 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0002_alter_trainer_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
